# Generated by Django 4.2.11 on 2024-03-11 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_recognition_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadedImage',
        ),
    ]
